### ISSUE TITLE
Does not build with Swift Package Manager

### ISSUE THREAD

**Issue by erikt** [kpishere/POSIXSerialPort#2]
Building with Swift Package Manager terminates with a fatal error.

I _think_ the syntax in the `Package.swift` manifest, is for swift-tools-versions' more recent than 5.0, but the swift-tools-version directive in the manifest, is for swift-tools-version: 4.2

If the directive is changed to anything equal to or later than 5.0, building works.

**Comment by kpishere** [comment]
An update has been made to fix this issue. #3
